# Generated by Django 6.0 on 2025-12-04 20:51

import ckeditor.fields
import django.db.models.deletion
import portfolio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Recommended size: 1500x500px', null=True, upload_to=portfolio.models.user_directory_path)),
                ('profile_image', models.ImageField(blank=True, help_text='Recommended size: 400x400px', null=True, upload_to=portfolio.models.user_directory_path)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('theme_color', models.CharField(default='#0073b1', help_text='Main theme color (hex)', max_length=7)),
                ('accent_color', models.CharField(blank=True, default='#333333', help_text='Accent color (hex)', max_length=7, null=True)),
                ('show_phone', models.BooleanField(default=False, verbose_name='Show phone publicly')),
                ('show_email', models.BooleanField(default=False, verbose_name='Show email publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Profile',
                'verbose_name_plural': 'Portfolio Profiles',
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=portfolio.models.user_directory_path)),
                ('file_type', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('pdf', 'PDF'), ('psd', 'PSD File'), ('ai', 'AI File'), ('figma', 'Figma File'), ('sketch', 'Sketch File'), ('other', 'Other')], max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Logos, Mockups, Wireframes', max_length=100, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=300, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to=portfolio.models.user_directory_path)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('degree', models.CharField(blank=True, max_length=200, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to=portfolio.models.user_directory_path)),
                ('institution_url', models.URLField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('issuing_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Leave blank if never expires', null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100, null=True)),
                ('credential_url', models.URLField(blank=True, help_text='URL to verify credential', null=True)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-issue_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('technologies', models.CharField(blank=True, help_text='Comma-separated list', max_length=500, null=True)),
                ('project_url', models.URLField(blank=True, null=True, verbose_name='Live Demo URL')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub Repository URL')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, help_text='Project thumbnail image', null=True, upload_to=portfolio.models.user_directory_path)),
                ('featured', models.BooleanField(default=False, help_text='Feature this project prominently')),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SectionVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_about', models.BooleanField(default=True, verbose_name='About Section')),
                ('show_experience', models.BooleanField(default=True, verbose_name='Experience Section')),
                ('show_education', models.BooleanField(default=True, verbose_name='Education Section')),
                ('show_skills', models.BooleanField(default=True, verbose_name='Skills Section')),
                ('show_projects', models.BooleanField(default=True, verbose_name='Projects Section')),
                ('show_certifications', models.BooleanField(default=True, verbose_name='Certifications Section')),
                ('show_media', models.BooleanField(default=True, verbose_name='Media Gallery Section')),
                ('show_contact', models.BooleanField(default=True, verbose_name='Contact Section')),
                ('layout_style', models.CharField(choices=[('linkedin', 'LinkedIn Style'), ('minimal', 'Minimal'), ('creative', 'Creative'), ('corporate', 'Corporate')], default='linkedin', max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visibility', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Section Visibility',
                'verbose_name_plural': 'Section Visibility Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Programming, Design, Tools', max_length=100, null=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class (e.g., fab fa-python)', max_length=100, null=True)),
                ('proficiency', models.IntegerField(blank=True, default=0, help_text='Percentage (0-100)', null=True)),
                ('order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
