# Generated by Django 6.0 on 2025-12-04 21:40

import ckeditor.fields
import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('section_type', models.CharField(choices=[('custom', 'Custom Section'), ('text', 'Text Content'), ('gallery', 'Image Gallery'), ('testimonials', 'Testimonials'), ('services', 'Services'), ('awards', 'Awards & Honors'), ('publications', 'Publications'), ('languages', 'Languages'), ('hobbies', 'Hobbies & Interests'), ('volunteer', 'Volunteer Work')], default='custom', max_length=50)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Main content for the section', null=True)),
                ('show_title', models.BooleanField(default=True, help_text='Show section title')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon (e.g., fas fa-award)', max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section')),
                ('layout_style', models.CharField(choices=[('default', 'Default'), ('card', 'Card Style'), ('minimal', 'Minimal'), ('highlight', 'Highlight')], default='default', max_length=50)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_sections', to='portfolio.profile')),
            ],
            options={
                'verbose_name': 'Dynamic Section',
                'verbose_name_plural': 'Dynamic Sections',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=portfolio.models.user_directory_path)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_text', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('url_text', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.dynamicsection')),
            ],
            options={
                'verbose_name': 'Section Item',
                'verbose_name_plural': 'Section Items',
                'ordering': ['order', '-is_featured', 'title'],
            },
        ),
    ]
