# Generated by Django 6.0.1 on 2026-02-26 19:46

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_systemconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicsection',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='Main content for the section', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
