# Generated by Django 6.0.1 on 2026-02-26 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_dynamicsection_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional: attach this media to a specific project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_files', to='portfolio.project'),
        ),
    ]
