# Generated by Django 6.0.1 on 2026-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_mediafile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allow_media_download',
            field=models.BooleanField(default=True, help_text="Allow visitors to download this project's media files"),
        ),
        migrations.AddField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Mark this project as completed'),
        ),
    ]
