# Generated by Django 6.0.1 on 2026-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_allow_media_download_project_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='allow_download',
            field=models.BooleanField(default=True, help_text='Allow this specific media file to be downloaded'),
        ),
    ]
