# Generated by Django 6.0 on 2026-04-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_systemconfiguration_seo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='behance',
            field=models.URLField(blank=True, null=True, verbose_name='Behance URL'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='WhatsApp URL'),
        ),
    ]
