# Generated by Django 6.0 on 2026-04-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_behance_profile_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='auto_reply_enabled',
            field=models.BooleanField(
                default=True, help_text='Automatically send a confirmation email to people who submit the contact form.'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='auto_reply_message',
            field=models.TextField(default='Hello {name},\n\nThank you for contacting me through my portfolio website. I have received your message and will get back to you as soon as possible.\n\nYour message summary:\nSubject: {subject}\nMessage: {message}\n\nBest regards,\n{site_name}\n{support_email}',
                                   help_text='Placeholders supported: {name}, {email}, {subject}, {message}, {site_name}, {support_email}'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='auto_reply_subject',
            field=models.CharField(
                default='Thanks for contacting {site_name}', help_text='Placeholders supported: {name}, {subject}, {site_name}', max_length=255),
        ),
    ]
