# Generated by Django 6.0 on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_systemconfiguration_auto_reply_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionvisibility',
            name='nav_about_order',
            field=models.PositiveIntegerField(default=10, help_text='Navbar position for About link'),
        ),
        migrations.AddField(
            model_name='sectionvisibility',
            name='nav_contact_order',
            field=models.PositiveIntegerField(default=70, help_text='Navbar position for Contact link'),
        ),
        migrations.AddField(
            model_name='sectionvisibility',
            name='nav_education_order',
            field=models.PositiveIntegerField(default=30, help_text='Navbar position for Education link'),
        ),
        migrations.AddField(
            model_name='sectionvisibility',
            name='nav_experience_order',
            field=models.PositiveIntegerField(default=20, help_text='Navbar position for Experience link'),
        ),
        migrations.AddField(
            model_name='sectionvisibility',
            name='nav_media_order',
            field=models.PositiveIntegerField(default=60, help_text='Navbar position for Media link'),
        ),
        migrations.AddField(
            model_name='sectionvisibility',
            name='nav_projects_order',
            field=models.PositiveIntegerField(default=40, help_text='Navbar position for Projects link'),
        ),
        migrations.AddField(
            model_name='sectionvisibility',
            name='nav_skills_order',
            field=models.PositiveIntegerField(default=50, help_text='Navbar position for Skills link'),
        ),
    ]
