# Generated by Django 5.2.8 on 2026-04-24  

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_sectionvisibility_navbar_order_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='favicon_image',
            field=models.ImageField(blank=True, help_text='Upload a favicon image for the site header/browser tab. Recommended: square PNG or JPG.', null=True, upload_to='site_assets/'),
        ),
    ]
